const characterTemplates = [
  'assets/cards/templates/character/Blank_Character_Template.png',
  'assets/cards/templates/character/Blank_Character_Template.png',
  //BOTTOM IS TEMP
  'assets/cards/templates/startingitems/Border_Eternal_Active_Attackable.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active_Dice.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active_NoPaper.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active.png',
  'assets/cards/templates/startingitems/Border_Eternal_Passive_Attackable.png',
  'assets/cards/templates/startingitems/Border_Eternal_Passive_Dice.png' ,
  'assets/cards/templates/startingitems/Border_Eternal_Passive_NoPaper.png' ,
  'assets/cards/templates/startingitems/Border_Eternal_Passive.png',
  'assets/cards/templates/startingitems/Border_Eternal_Revenant.png' ,
  'assets/cards/templates/treasure/Blank_Treasure_Dice.png',
  'assets/cards/templates/treasure/Blank_Treasure_Haunted.png',
  'assets/cards/templates/treasure/Blank_Treasure.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_Attackable.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_Dice.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_Haunted.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_NoPaper.png',
  'assets/cards/templates/treasure/Border_Treasure_Active.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_Attackable.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_Dice.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_Haunted.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_NoPaper.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive.png',
];

const _startingitems_templates = [
  'assets/cards/templates/character/Blank_Character_Template.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active_Attackable.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active_Dice.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active_NoPaper.png',
  'assets/cards/templates/startingitems/Border_Eternal_Active.png',
  'assets/cards/templates/startingitems/Border_Eternal_Passive_Attackable.png',
  'assets/cards/templates/startingitems/Border_Eternal_Passive_Dice.png' ,
  'assets/cards/templates/startingitems/Border_Eternal_Passive_NoPaper.png' ,
  'assets/cards/templates/startingitems/Border_Eternal_Passive.png',
  'assets/cards/templates/startingitems/Border_Eternal_Revenant.png' ,
];

const _treasure_templates = [
  'assets/cards/templates/treasure/Blank_Treasure_Dice.png',
  'assets/cards/templates/treasure/Blank_Treasure_Haunted.png',
  'assets/cards/templates/treasure/Blank_Treasure.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_Attackable.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_Dice.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_Haunted.png',
  'assets/cards/templates/treasure/Border_Treasure_Active_NoPaper.png',
  'assets/cards/templates/treasure/Border_Treasure_Active.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_Attackable.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_Dice.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_Haunted.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive_NoPaper.png',
  'assets/cards/templates/treasure/Border_Treasure_Passive.png',
];